name: Pull request
on:
  pull_request:
    types: [ opened, reopened, synchronize ]
jobs:
  pr-check:
    name: PR test for locking-cache
    runs-on: ubuntu-latest
    if: github.repository == 'ScientaNL/locking-cache'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - run: npm ci
      - run: npm run test
      - run: npm run lint
